/*
 * JSP generated by Resin-4.0.45 (built Thu, 06 Aug 2015 12:42:25 PDT)
 */

package _jsp._web_22dinf._classes._edu._drexel._cs461._examples;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.IOException;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class _user__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    edu.drexel.cs461.examples.Database db;
    db = (edu.drexel.cs461.examples.Database) pageContext.getAttribute("db");
    if (db == null) {
      db = new edu.drexel.cs461.examples.Database();
      pageContext.setAttribute("db", db);
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    
		request.setCharacterEncoding("UTF-8");
		String name = (String)session.getAttribute("user");

		String trucks = "select name as name from FoodTrucks";
		Connection conn = db.openDB("PgBundle");
		ResultSet rs = db.retrieveDB(conn,trucks);
	
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((name));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
	while(rs.next()) { 
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((rs.getString("name")));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((rs.getString("name")));
    out.write(_jsp_string6, 0, _jsp_string6.length);
     }
	rs.close();
	
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((name));
    out.write(_jsp_string8, 0, _jsp_string8.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -5881050986011397250L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/classes/edu/drexel/cs461/examples/user.jsp"), 8942376733864103799L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string8;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string2 = "\n	<h1>Hello, ".toCharArray();
    _jsp_string5 = "\">".toCharArray();
    _jsp_string3 = "</h1>\n	<h3>Rate a food truck</h3>\n	<form id=\"rate\" name=\"rate\" action=\"./rating\" method=\"post\">\n	<select name=\"trucks\" id=\"trucks\">\n	<option value=\"0\">Please select one</option>\n	".toCharArray();
    _jsp_string7 = "\n	</select><br><br>\n	Ratings:\n	<select name=\"rating\" id=\"rating\">\n		<option value=\"1\">1</option>\n		<option value=\"2\">2</option>\n		<option value=\"3\">3</option>\n		<option value=\"4\">4</option>\n		<option value=\"5\">5</option>\n	</select>\n	<br>\n	Comments:<br>\n	<input type=\"hidden\" name=\"user\" value=\"".toCharArray();
    _jsp_string8 = "\">\n	<textarea rows=\"4\" cols=\"50\" id=\"comment\" name=\"comment\" value = \"Leave your comments here...\">Leave your comments here...</textarea><br>\n	<input type=\"submit\" value=\"Submit\">\n	<a href=\"/~jw968/index\">Log out</a>\n	</form>\n</body>  \n</html> ".toCharArray();
    _jsp_string6 = "</option>\n	".toCharArray();
    _jsp_string4 = "\n		<option value=\"".toCharArray();
    _jsp_string0 = "  \n\n\n\n\n\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">  \n<html>  \n".toCharArray();
    _jsp_string1 = "\n<head>  \n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">  \n<title>Owner</title>  \n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n<script type=\"text/javascript\">  \n</script>  \n</head>  \n\n<body>\n	".toCharArray();
  }
}
